# Generated by Django 3.2.6 on 2021-08-16 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonemes',
            old_name='HebLetter',
            new_name='hebrewletter',
        ),
    ]
