# Generated by Django 3.2.6 on 2021-08-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hebword',
            name='word',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='latinscript',
            name='text',
            field=models.CharField(max_length=20),
        ),
    ]
