# Generated by Django 3.2.6 on 2021-08-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20210812_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonemes',
            name='hebWord',
        ),
        migrations.AlterField(
            model_name='phonemes',
            name='text',
            field=models.CharField(max_length=3),
        ),
    ]
