# Generated by Django 3.2.6 on 2021-08-16 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_rename_hebletter_phonemes_hebrewletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonemes',
            old_name='hebrewletter',
            new_name='hebletter',
        ),
    ]
