# Generated by Django 3.2.6 on 2021-08-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_rename_hebrewletter_phonemes_hebletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonemes',
            name='hebletter',
        ),
        migrations.AddField(
            model_name='phonemes',
            name='hebletter',
            field=models.ManyToManyField(blank=True, null=True, to='dictionary.HebLetter'),
        ),
    ]
