# Generated by Django 3.2.6 on 2021-08-13 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20210812_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='HebLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='phonemes',
            name='HebLetter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.hebletter'),
        ),
    ]
