# Generated by Django 3.2.6 on 2021-08-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_auto_20210816_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='hebword',
            name='definition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hebword',
            name='partOfSpeech',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hebword',
            name='root',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='hebword',
            name='transliteration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hebword',
            name='word',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
