# Generated by Django 3.2.6 on 2021-08-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_auto_20210817_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hebword',
            name='root',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
