# Generated by Django 3.2.6 on 2021-08-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_alter_hebword_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hebword',
            name='partOfSpeech',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
